server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://synspeechdb.cmn5b0a2bh6p.us-east-1.rds.amazonaws.com:5432/users?ssl=true&sslmode=verify-full&sslrootcert=src/main/resources/us-east-1-bundle.pem
    username: pacoeco
    password: jfaap234
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 4aruvisqmaoigb217hij76aju5
            scope:
              - phone
              - openid
              - email
            redirect-uri: https://d84l1y8p4kdic.cloudfront.net
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_9K4qyEk4E
            user-name-attribute: username

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

aws:
  cognito:
    userPoolId: us-east-1_czPnvGGWd
    clientId: 4aruvisqmaoigb217hij76aju5
    clientSecret: 1l0bf8ccp78namk5u5l2b7fbqrquerra4hqi915mirb3alv13a6n

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
